### PR TITLE
Revamp

### PR DESCRIPTION
**Pull request by TheScarastic**

### CODE REVIEW

**Comment by Yash-Garg** [comment]
DNM @akhilnarang

**Comment by akhilnarang** [comment]
```
Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property sharedPref has not been initialized
       at in.thescriptgroup.attendance.adapter.ListAdapter.getSharedPref(ListAdapter.kt:20)
       at in.thescriptgroup.attendance.adapter.ListAdapter.getSubjectDetails(ListAdapter.kt:104)
       at in.thescriptgroup.attendance.adapter.ListAdapter.onBindViewHolder$lambda-0(ListAdapter.kt:127)
       at in.thescriptgroup.attendance.adapter.ListAdapter.$r8$lambda$1_XdWgc5Tv3UcM3sUV5H8Q05C5U()
       at in.thescriptgroup.attendance.adapter.ListAdapter$$ExternalSyntheticLambda0.onClick(:6)
       at android.view.View.performClick(View.java:7448)
       at android.view.View.performClickInternal(View.java:7425)
       at android.view.View.access$3600(View.java:810)
       at android.view.View$PerformClick.run(View.java:28305)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)```

With a signed release build

**Comment by rittmang** [comment]
@akhilnarang

**Comment by Yash-Garg** [comment]
@akhilnarang test now, should work fine.

**Comment by Yash-Garg** [comment]
Merge wen @akhilnarang

**Pull request merged**
